name: Terraform CI CD Pipline for deplying the resources
run-name: ${{ github.actor}} has triggered the Pipline

on:
  push:
    branches:
      - 'stage'
  
jobs:
  build-infra:
    name: terraform ci-cd
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v4
      

      - name: Configure AWS Credential 
        uses: aws-actions/configure-aws-credentials@v4
        with:
          AWS_ACCESS_KEY: ${{ secrets.AWS_ACCESS_KEY }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_SESSION_TOKEN: ${{ secrets.AWS_SESSION_TOKEN}}
          AWS_REGION: us-east-1


      - name: Set up Terraform 
        uses: hashicorp/setup-terraform@v2
      - name: Terraform init
        id: init
        run: terraform init
        working-directory: ./terraform
      - name: Terraform validate
        id: validate
        run: terraform validate
        working-directory: ./terraform
      - name: Terraform plan
        id: plan
        run: terraform plan
        working-directory: ./terraform
      - name: Terraform apply
        id: apply
        run: terraform apply --auto-approve
        working-directory: ./terraform
  
  # docker-build:
  #   runs-on: ubuntu-latest
  #   steps:

  #    - name: Configure AWS Credentials
  #      uses: aws-actions/configure-aws-credentials
  #      with:
  #       AWS_ACCESS_KEY: ${{ secrets.AWS_ACCESS_KEY }}
  #       AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
  #       AWS_SESSION_TOKEN: ${{ secrets.AWS_SESSION_TOKEN }}
  #       AWS_REGION: us-east-1

  #    - name: checkout
  #      uses: actions/checkout@v4
     

  #    - name: Build docker image form app
  #      run: docker build -t shashank-python-image:latest ./app

  #    - name: Save the docker image to specific location 
  #      run: docker save -o shashank-python-image.tar shashank-python-image:latest


  #    - name: install boto3 and botocore
  #      run: pip3 install boto3 botocore

  #    - name: upload docker image to s3
  #      run: aws s3 cp shashank-python-image.tar s3://intern-2-s3-bucket/shashank-python-image.tar







